//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtiquetasArca.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15, 15")]
        public global::System.Drawing.Point WindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["WindowLocation"]));
            }
            set {
                this["WindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LAS MEJORES LAVADORAS, S.A. de C.V.")]
        public string CompanyNameLine1 {
            get {
                return ((string)(this["CompanyNameLine1"]));
            }
            set {
                this["CompanyNameLine1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R.F.C.: MLA-031024-CK1")]
        public string CompanyNameLine2 {
            get {
                return ((string)(this["CompanyNameLine2"]));
            }
            set {
                this["CompanyNameLine2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Calle Félix Merino # 2011")]
        public string FiscalAddressLine1 {
            get {
                return ((string)(this["FiscalAddressLine1"]));
            }
            set {
                this["FiscalAddressLine1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Oasis Revolución 2")]
        public string FiscalAddressLine2 {
            get {
                return ((string)(this["FiscalAddressLine2"]));
            }
            set {
                this["FiscalAddressLine2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cd. Juárez, Chih. C.P. 32674")]
        public string FiscalAddressLine3 {
            get {
                return ((string)(this["FiscalAddressLine3"]));
            }
            set {
                this["FiscalAddressLine3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Av. Juárez # 4710")]
        public string AddressLine1 {
            get {
                return ((string)(this["AddressLine1"]));
            }
            set {
                this["AddressLine1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Col. Arquitectos")]
        public string AddressLine2 {
            get {
                return ((string)(this["AddressLine2"]));
            }
            set {
                this["AddressLine2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chihuahua, Chih. C.P. 31000")]
        public string AddressLine3 {
            get {
                return ((string)(this["AddressLine3"]));
            }
            set {
                this["AddressLine3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProductName {
            get {
                return ((string)(this["ProductName"]));
            }
            set {
                this["ProductName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Brand {
            get {
                return ((string)(this["Brand"]));
            }
            set {
                this["Brand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Model {
            get {
                return ((string)(this["Model"]));
            }
            set {
                this["Model"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Series {
            get {
                return ((string)(this["Series"]));
            }
            set {
                this["Series"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint SerialNumberStart {
            get {
                return ((uint)(this["SerialNumberStart"]));
            }
            set {
                this["SerialNumberStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public uint SerialNumberEnd {
            get {
                return ((uint)(this["SerialNumberEnd"]));
            }
            set {
                this["SerialNumberEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127 V ~      60  Hz     9,8  A")]
        public string Specs {
            get {
                return ((string)(this["Specs"]));
            }
            set {
                this["Specs"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<RSAKeyValue><Modulus>v3kCP6svDZT8cGX8h+bVUfCOFwjU6s+IqT+pIX3x0NHe0xqnpUMN93glKYEwJmynn6V6lhjMDt0Wqb+MD1DUQK+rajbZHT2jEEJzqSSoWPKf6+rO6J6AnQDB1DeEHKNw2wq2Po7CWJXF9+21jvADA4zYYvP1nTL8hMxo3bslZHCHD+v5INWZQdBBF3EF1RmsEiRGHVGBTfiMJyK7FIOqHEqKII6KepGCIRIuJXmWjhcFEf7Tlv6UmcSyiVGJ+bsWcJHsMwu0FHMV5grHk7oGIw4omSvkGLbaZwFPqySAJsiBRF7wBEEhhXYCBElnP5dAsa1klsXp4hpNq19TsuZVWQ==</Modulus><Exponent>AQAB</Exponent></RSAKeyValue>")]
        public string PublicKey {
            get {
                return ((string)(this["PublicKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2DFCF687-97B7-47D7-A1BF-B7044F76ED2E")]
        public string CLSID {
            get {
                return ((string)(this["CLSID"]));
            }
        }
    }
}
