//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseGenerator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<RSAKeyValue><Modulus>v3kCP6svDZT8cGX8h+bVUfCOFwjU6s+IqT+pIX3x0NHe0xqnpUMN93glKYE" +
            "wJmynn6V6lhjMDt0Wqb+MD1DUQK+rajbZHT2jEEJzqSSoWPKf6+rO6J6AnQDB1DeEHKNw2wq2Po7CWJX" +
            "F9+21jvADA4zYYvP1nTL8hMxo3bslZHCHD+v5INWZQdBBF3EF1RmsEiRGHVGBTfiMJyK7FIOqHEqKII6" +
            "KepGCIRIuJXmWjhcFEf7Tlv6UmcSyiVGJ+bsWcJHsMwu0FHMV5grHk7oGIw4omSvkGLbaZwFPqySAJsi" +
            "BRF7wBEEhhXYCBElnP5dAsa1klsXp4hpNq19TsuZVWQ==</Modulus><Exponent>AQAB</Exponent>" +
            "<P>wcUGoNMDXs6raJsBExI2v3cokVlV8O++YXvpkzO1uFT01WrXju1fqK8RwAHP9yQ3JmSwqevh34Vyg" +
            "VKzPmExkNc4jBDx1Qh94ANXoydmd5mAb5JBwaG5kpc3BnnFLus0Bz+DPUKMFJmzlGeqf7jmkZD/QJZiy" +
            "EX9INWO68+s+Jc=</P><Q>/PcjLPPKILTFHu4Z/gt/UoZyj0VGhqCZWJw5COWXgZf/c3r5ZV1yBdswIe" +
            "s3hQy4BKQ7Ppa0sMNwMcohnrLAkvU3FWsHxcoZx3SWXZtLYsrUxap+AG7wguLd5XCsSvo/n8WuoMyOYg" +
            "3NMYGPPT/A/AI9zTUTM7euxsp3K3wyb48=</Q><DP>dSCi3A4RaHqm1Cl2IdANtfjSVeHZeDWDMCwVyb" +
            "wlKVJ5WJQnzqaf/zgsE5NE4ZBLofKVc3E5bMKer5uM67UWoAXokYoglHR4mjOLAv1rC/qGz2pqQyB+Ky" +
            "UqxshOsAjOv17d9ubGBCHQknGDd4cOIIm0MZd2CLd9xh4xMUuss+s=</DP><DQ>UqzGz0tCFVxfTFOPJ" +
            "StGyobsbAy9FwTn+UDdlx3KXW167JgVaF6ZBHb1jTBd7dsRTVsLjdIdbeQCCBPC1yYesCj6fsKDQM5jj" +
            "H97IU6+3aPi1FN7aNLZQj25PeKMPNj68FHgV+di5YMTPAnW8bKjdPmajzW4d9+hfJDxT8IAjds=</DQ>" +
            "<InverseQ>WZCejQveGNrWetWRPvYDXWW02SRr7XLoZZc7NZ/AsqmIEIgsuX0Jo7/f22ATVN0lmFd7uP" +
            "tkIYqUSowCCI1o/47u0dLCfkbFDGw7HQYq9UGMXPW1saAwINTsDvjMA9NUaXhsRbe7/riTq2NA8+fS5B" +
            "+tt805Rtys/iUV848HOi8=</InverseQ><D>rYQ9DHPWhUlx524VBxeiU8pbCfbf9Rcz8qUVYZugC6xV" +
            "cRvjtzloK86+ZrmDaB7pXRz6VZGNQx8KjbRfefW3FBPelLe10/DqmC6QYEUvJsRhNsuozFfvl9h6zxWs" +
            "bMOU33v6ogB/kQXRzRenhCxvnsUBx9Lrz5TIEJSpp98USMq4UmdRIBrdMY/QOXQd/B+QH3IV/5iShj16" +
            "f0uNx/ySd+OD43ax5v3BAxgrKrAEwkz+I2D4lpqY5q+X6Lmneem8MhA9g2AscWkozzLW3dG4yvMS37vC" +
            "r2bbAxZKY/QZBBWgXsY6Ut7C07iMyr1Mg1JwEXKexUre/Dcr1Lb+rSMyzQ==</D></RSAKeyValue>")]
        public string PrivateKey {
            get {
                return ((string)(this["PrivateKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<RSAKeyValue><Modulus>v3kCP6svDZT8cGX8h+bVUfCOFwjU6s+IqT+pIX3x0NHe0xqnpUMN93glKYEwJmynn6V6lhjMDt0Wqb+MD1DUQK+rajbZHT2jEEJzqSSoWPKf6+rO6J6AnQDB1DeEHKNw2wq2Po7CWJXF9+21jvADA4zYYvP1nTL8hMxo3bslZHCHD+v5INWZQdBBF3EF1RmsEiRGHVGBTfiMJyK7FIOqHEqKII6KepGCIRIuJXmWjhcFEf7Tlv6UmcSyiVGJ+bsWcJHsMwu0FHMV5grHk7oGIw4omSvkGLbaZwFPqySAJsiBRF7wBEEhhXYCBElnP5dAsa1klsXp4hpNq19TsuZVWQ==</Modulus><Exponent>AQAB</Exponent></RSAKeyValue>")]
        public string PublicKey {
            get {
                return ((string)(this["PublicKey"]));
            }
        }
    }
}
